[FIX]yml formatting

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -19,18 +19,18 @@ jobs:
         container: ghcr.io/epitech/coding-style-checker:latest
         steps:
             - name: Checkout GH repository
-                uses: actions/checkout@v4
-                with:
-                    repository: ''
+              uses: actions/checkout@v4
+              with:
+                  repository: ''
             - name: Run coding-style
-                run: check.sh $(pwd) $(pwd)
+              run: check.sh $(pwd) $(pwd)
             - name: Check coding-style errors
-                run: |
-                    input=$(pwd)/coding-style-reports.log
-                    awk -F':' '{print "::error title="$3" coding style error,file="$1",line="$2"::"$4}' $input
-                    if [ -s $input ]; then
-                        exit 1
-                    fi
+              run: |
+                  input=$(pwd)/coding-style-reports.log
+                  awk -F':' '{print "::error title="$3" coding style error,file="$1",line="$2"::"$4}' $input
+                  if [ -s $input ]; then
+                      exit 1
+                  fi
     check_allow_function:
         runs-on: ubuntu-latest
         steps:
@@ -39,33 +39,33 @@ jobs:
               with:
                   repository: ''
             - name: Install dependencies
-                run: sudo apt-get update && sudo apt-get install libcsfml-dev
+              run: sudo apt-get update && sudo apt-get install libcsfml-dev
             - name: Check allowed functions
-                run: |
-                    echo "Running make"
-                    if [ -f Makefile ]; then
-                        make
-                        error=false
-                        IFS=',' read -ra ADDR <<< "${{ env.EXECUTABLES }}"
-                        for file in "${ADDR[@]}"; do
-                            if [ ! -x "$file" ]; then
-                                echo "::error file=${file#./},title=File does not exist or is not executable::${file#./}"
-                                error=true
-                            else
-                                functions=$(nm $file | grep '@' | cut -d'@' -f1 | awk '{print $NF}' | grep -v '__libc_start_main' | grep -v '__cxa_finalize')
-                                for func in $functions; do
-                                    if [[ "${{ env.ALLOW_FUNC }}" != *"$func"* ]]; then
-                                        echo "::error file=${func#./},title=Bannable function::${func#./}"
-                                        error=true
-                                    fi
-                                done
-                            fi
-                        done
-                        if $error; then
-                            exit 1
+              run: |
+                echo "Running make"
+                if [ -f Makefile ]; then
+                    make
+                    error=false
+                    IFS=',' read -ra ADDR <<< "${{ env.EXECUTABLES }}"
+                    for file in "${ADDR[@]}"; do
+                        if [ ! -x "$file" ]; then
+                            echo "::error file=${file#./},title=File does not exist or is not executable::${file#./}"
+                            error=true
+                        else
+                            functions=$(nm $file | grep '@' | cut -d'@' -f1 | awk '{print $NF}' | grep -v '__libc_start_main' | grep -v '__cxa_finalize')
+                            for func in $functions; do
+                                if [[ "${{ env.ALLOW_FUNC }}" != *"$func"* ]]; then
+                                    echo "::error file=${func#./},title=Bannable function::${func#./}"
+                                    error=true
+                                fi
+                            done
                         fi
+                    done
+                    if $error; then
+                        exit 1
                     fi
-                shell: bash
+                fi
+              shell: bash
     check_program_compilation:
         runs-on: ubuntu-latest
         needs:
@@ -73,25 +73,25 @@ jobs:
             - check_allow_function
         steps:
             - name: Checkout GH repo
-                uses: actions/checkout@v4
-                with:
-                    repository: ''
+              uses: actions/checkout@v4
+              with:
+                  repository: ''
             - name: Install dependencies
-                run: sudo apt-get update && sudo apt-get install libcsfml-dev
+              run: sudo apt-get update && sudo apt-get install libcsfml-dev
             - name: Compile project
-                run: |
-                    make
-                    make clean
+              run: |
+                make
+                make clean
               timeout-minutes: 2
             - name: Check file
-                run: |
-                    IFS=',' read -ra ADDR <<< "${{ env.EXECUTABLES }}"
-                    for file in "${ADDR[@]}"; do
-                        if [ ! -x "$file" ]; then
-                            echo "::error file=${file#./},title=File does not exist or is not executable::${file#./}"
-                            exit 1
-                        fi
-                    done
+              run: |
+                IFS=',' read -ra ADDR <<< "${{ env.EXECUTABLES }}"
+                for file in "${ADDR[@]}"; do
+                    if [ ! -x "$file" ]; then
+                        echo "::error file=${file#./},title=File does not exist or is not executable::${file#./}"
+                        exit 1
+                    fi
+                done
 
     run_tests:
         runs-on: ubuntu-latest
@@ -99,13 +99,13 @@ jobs:
         needs:  check_program_compilation
         steps:
             - name: Checkout GH repo
-                uses: actions/checkout@v4
-                with:
-                    repository: ''
+              uses: actions/checkout@v4
+              with:
+                  repository: ''
             - name: Install dependencies
-                run: sudo apt-get update && sudo apt-get install libcsfml-dev
+              run: sudo apt-get update && sudo apt-get install libcsfml-dev
             - name: Compile tests binaries
-                run: make tests_run
+              run: make tests_run
                 timeout-minutes: 2
     push_to_mirror:
         runs-on: ubuntu-latest
@@ -113,11 +113,11 @@ jobs:
         if: github.event_name == 'push'
         steps:
             - uses: actions/checkout@v4
-                with:
-                    fetch-depth: 0
+              with:
+                  fetch-depth: 0
             - uses: pixta-dev/repository-mirroring-action@v1.1.1
-                with:
-                    target_repo_url:
-                        ${{ env.MIRROR_URL }}
-                    ssh_private_key:
-                        ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+              with:
+                  target_repo_url:
+                      ${{ env.MIRROR_URL }}
+                  ssh_private_key:
+                      ${{ secrets.GIT_SSH_PRIVATE_KEY }}
